// <auto-generated />
namespace Hospital_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedoctorsnamepropertydatatypefrominttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedoctorsnamepropertydatatypefrominttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "202201222159526_change doctor's name property datatype from int to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
