// <auto-generated />
namespace Hospital_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedNewcoloumncalledtheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedNewcoloumncalledtheme));
        
        string IMigrationMetadata.Id
        {
            get { return "202202181826438_added New coloumn called theme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
